name: Check links
on: 
  - pull_request
  - push
jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # hugo version should match netlify.toml
          hugo-version: '0.78.2'
          extended: true

      - name: Check links
        run: make check-all-links
