name: Check links
on: 
  - pull_request
  - push
jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check links
        run: make check-all-links
